#!/bin/bash
set -o pipefail
set -o nounset
bootstrap() {

	case "$(uname -s)" in

	Darwin)
		echo 'Mac OS X'
		;;

	Linux)
		DISTRO_ID=$(lsb_release -is)

		SUPPORTED_DEBIAN_ID=("Pop Ubuntu Debian")
		SUPPORTED_REDHAT_ID=("Fedora")

		# Debian based distro
		if [[ " ${SUPPORTED_DEBIAN_ID[*]} " =~ ${DISTRO_ID} ]]; then
			dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
			source "${dir}/debInstall.sh"
		elif
			[[ " ${SUPPORTED_REDHAT_ID[*]} " =~ ${DISTRO_ID} ]]
		then
			echo "Redhat based distro..."
		else
			echo"Linux distro not supported!"
		fi

		# fix ubuntu snap crap
		if [[ "${DISTRO_ID}" == "Ubuntu" ]]; then
			echo "Replacing firexfox snap with deb package..."
			sudo snap remove firefox
			sudo add-apt-repository ppa:mozillateam/ppa -y
			echo '
Package: *
Pin: release o=LP-PPA-mozillateam
Pin-Priority: 1001
' | sudo tee /etc/apt/preferences.d/mozilla-firefox

			echo 'Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:${distro_codename}";' | sudo tee /etc/apt/apt.conf.d/51unattended-upgrades-firefox
			sudo apt-get install firefox -y
		fi

		;;

	CYGWIN* | MINGW32* | MSYS* | MINGW*)
		echo 'MS Windows is not supported!'
		;;

	# Add here more strings to compare
	# See correspondence table at the bottom of this answer

	*)
		echo 'OS not supported!'
		;;
	esac
}

if [ -d "${HOME}/.oh-my-zsh" ]; then
	read -rp "Delete existing .oh-my-zsh folder? (y/N): " DELETE_OH_MY_ZSH
	if [[ $DELETE_OH_MY_ZSH == "y" ]]; then
		rm -rf "$HOME/.oh-my-zsh"
	fi
fi
if [ -d "${HOME}/.local/share/nvim" ]; then
	read -rp "Delete existing Neovim config? (y/N): " DELETE_NEOVIM_CONFIG
	if [[ $DELETE_NEOVIM_CONFIG == "y" ]]; then
		rm -rf "$HOME/.local/share/nvim"
		rm -rf "$HOME/.config/nvim/plugin"
	fi
fi
bootstrap
